language: python
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
env:
  - TOXENV=py34
  - TOXENV=py35
install:
  - virtualenv -p python3 /tmp/env
  - /tmp/env/bin/pip install tox coveralls
script:
  - /tmp/env/bin/tox
